export enum PhytaromaTextResources {
    phytaromaTitle = "PhytAroma",
    wikiphytoTitle = "Wikiphyto",
    footerCopyright = "Copyright © ",
    footerGitHubLink = "https://github.com/clemalex06",
    footerLabelLink = "Suivez moi sur GitHub",
    footerDescription = "Le moteur de recherche de phytothérapie inspiré par ",
    topDescriptionWikiphytoLink = "http://www.wikiphyto.org/wiki/Accueil",
    topDescriptionButtonDisplayFamilyPlant = "Afficher la liste des famille de plantes",
    topDescriptionSearchResults = "Résultats de la recherche",
    topDescriptionButtonNewSearch = "Nouvelle Recherche",
    plantDetailNoInformation = "Aucune information disponible",
    linkOnWikiphyto = "Ouvrir sur Wikiphyto",
    planDetailGoBackFamilyPlant = "Revenir à la famille de cette plante",
    planDetailGoBackSearchResult = "Revenir aux résultats de la recherche",
    viewDetailLabel = "Voir le détail",
    plantFamilyListLabel = "Liste des familles de plantes",
    plantFamilyLabel = "Famille de plantes : ",
    plantDetailLabel = "Fiche la plante : ",
    shortDescriptionLabel = "le moteur de recherche inspiré par ",
    longDescriptionLabel = 'PhytAroma est un moteur de recherche intuitif permettant de rechercher'
    + ' de nombreuses plantes utilisées en phytothérapie et Aromathérapie.'
    + ' Il propose une interface facile pour afficher les informations présentes sur ',
    searchLabel = "Entrez un mot clé de recherche",
    name = "Nom",
    description = "Description",
    history = "Histoire",
    dosis = "Dose",
    composition = "Composition",
    healthProperty = "Propriété de santé",
    indications = "Indications",
    undesirableEffects = "Effets indésirables",
}