export enum PhytaromaTextResources {
    phytaromaTitle = "PhytAroma",
    wikiphytoTitle = "Wikiphyto",
    footerCopyright = "Copyright © ",
    footerGitHubLink = "https://github.com/clemalex06",
    footerLabelLink = "Suivez moi sur GitHub",
    footerDescription = "Le moteur de recherche de phytothérapie inspiré par ",
    topDescriptionWikiphytoLink = "http://www.wikiphyto.org/wiki/Accueil",
    topDescriptionButtonDisplayFamilyPlant = "Afficher la liste des famille de plantes",
    topDescriptionButtonNewSearch = "Nouvelle Recherche",
    plantDetailNoInformation = "Aucune information disponible",
    linkOnWikiphyto = "Ouvrir sur Wikiphyto",
    planDetailGoBackFamilyPlant = "Revenir à la famille de cette plante",
    viewDetailLabel = "Voir le détail",
    plantFamilyListLabel = "Liste des familles de plantes",
}